try:
    print(1)
    f
except:
    raise Exception
try:
    print(1)
except:
    print(2)